export const categories = [
    "Food",
    "Shopping",
    "Services",
    "Laundry",
    "Phone",
    "House",
    "Car",
    "Technology",
    "Water",
    "Energy",
    "Gas",
    "Clothing",
    "Education",
    "Health care",
    "Savings",
    "Transportation",
    "Insurance",
    "Entertainment and recreation",
    "Gasoline and motor fuels",
    "Travel",
    "Labor costs",
];